In [6]:
import pandas as pd
import numpy as np

In [158]:
df = pd.read_csv("sample_data.csv")

In [159]:
# The students can perform:
#     • Rename columns 
df=df.rename(columns={"Emp ID":"Employee ID","Years Exp":"Years of Experience"}) 
df

,Employee ID,Employee Name,AGE,Skill Set,Years of Experience,Salary (INR),Date Of Joining,Department,Remarks
0,EMP001,Rahul Sharma,25,Python,2,450000,12-01-2023,IT,Good
1,EMP002,Anita Devi,28,Java,4,600000,2022/05/11,IT,NaN
2,EMP003,Kiran Kumar,31,python,5,720000,15-Jan-2021,IT,Excellent
3,EMP004,Priya Nair,29,Data Science,3,650000,2021-07-20,Analytics,NaN
4,EMP005,Arjun,27,C++,2,520000,10/10/2022,Development,Good
...,...,...,...,...,...,...,...,...,...
86,EMP086,Koushik,28,Machine Learning,4,720000,2021-12-12,AI,NaN
87,EMP087,Aarthi,24,Python,1,350000,2024-01-10,IT,NaN
88,EMP088,Pradeep,33,Data Science,8,1100000,2016-04-14,Analytics,NaN
89,EMP089,Rohini,29,SQL,4,650000,2021-08-20,Database,NaN
90,EMP090,Vijay,28,C++,3,580000,2022-09-09,Development,NaN

In [36]:
#  remove duplicates
df.drop_duplicates()
df

,Employee ID,Employee Name,AGE,Skill Set,Years of Experience,Salary (INR),Date Of Joining,Department,Remarks
0,EMP001,Rahul Sharma,25,Python,2,450000,12-01-2023,IT,Good
1,EMP002,Anita Devi,28,Java,4,600000,2022/05/11,IT,NaN
2,EMP003,Kiran Kumar,31,python,5,720000,15-Jan-2021,IT,Excellent
3,EMP004,Priya Nair,29,Data Science,3,650000,2021-07-20,Analytics,NaN
4,EMP005,Arjun,27,C++,2,520000,10/10/2022,Development,Good
...,...,...,...,...,...,...,...,...,...
86,EMP086,Koushik,28,Machine Learning,4,720000,2021-12-12,AI,NaN
87,EMP087,Aarthi,24,Python,1,350000,2024-01-10,IT,NaN
88,EMP088,Pradeep,33,Data Science,8,1100000,2016-04-14,Analytics,NaN
89,EMP089,Rohini,29,SQL,4,650000,2021-08-20,Database,NaN
90,EMP090,Vijay,28,C++,3,580000,2022-09-09,Development,NaN

In [33]:
#     • Handle null values (drop) 
df.dropna()

,Employee ID,Employee Name,AGE,Skill Set,Years of Experience,Salary (INR),Date Of Joining,Department,Remarks
0,EMP001,Rahul Sharma,25,Python,2,450000,12-01-2023,IT,Good
2,EMP003,Kiran Kumar,31,python,5,720000,15-Jan-2021,IT,Excellent
4,EMP005,Arjun,27,C++,2,520000,10/10/2022,Development,Good

In [55]:
# • Handle null values (fill)
df.fillna({"Employee ID": 000,"Employee Name": "abcd","AGE": 20,"Remarks": "good"}, inplace=True)
df

,Employee ID,Employee Name,AGE,Skill Set,Years of Experience,Salary (INR),Date Of Joining,Department,Remarks
0,EMP001,Rahul Sharma,25,Python,2,450000,12-01-2023,IT,Good
1,EMP002,Anita Devi,28,Java,4,600000,2022/05/11,IT,0
2,EMP003,Kiran Kumar,31,python,5,720000,15-Jan-2021,IT,Excellent
3,EMP004,Priya Nair,29,Data Science,3,650000,2021-07-20,Analytics,0
4,EMP005,Arjun,27,C++,2,520000,10/10/2022,Development,Good
...,...,...,...,...,...,...,...,...,...
86,EMP086,Koushik,28,Machine Learning,4,720000,2021-12-12,AI,0
87,EMP087,Aarthi,24,Python,1,350000,2024-01-10,IT,0
88,EMP088,Pradeep,33,Data Science,8,1100000,2016-04-14,Analytics,0
89,EMP089,Rohini,29,SQL,4,650000,2021-08-20,Database,0
90,EMP090,Vijay,28,C++,3,580000,2022-09-09,Development,0

In [57]:
#     • Change data types 
print(df.dtypes)

Employee ID            object
 Employee Name         object
AGE                    object
Skill Set              object
Years of Experience    object
Salary (INR)           object
Date Of Joining        object
Department             object
Remarks                object
dtype: object

In [75]:
print(df["Age"].unique())

['25' '28' '31' '29' '27' 0 '35' '22' '45' '30' 26 '24' '26' '32' '150'
 '-5' '33' '34' '23']

In [81]:
print(df["Age"].dtype)
print(df["Age"].head(10))

int64
0    25
1    28
2    31
3    29
4    27
5    28
6    35
7    22
8    45
9    30
Name: Age, dtype: int64

In [84]:
print(df["Years of Experience"].unique())

['2' '4' '5' '3' '10' '1' '18' '6' '7' '8' 0 'three' '0' '-2' '40' '9']

In [163]:
df["Years of Experience"] = df["Years of Experience"].replace("three", 3)
df["Years of Experience"] = pd.to_numeric(df["Years of Experience"],errors="coerce")
df["Years of Experience"] = df["Years of Experience"].fillna(df["Years of Experience"].median())
df["Years of Experience"] = df["Years of Experience"].astype(int)
df.head()

,Employee ID,Employee Name,AGE,Skill Set,Years of Experience,Salary (INR),Date Of Joining,Department,Remarks
0,EMP001,Rahul Sharma,25,Python,2,450000,12-01-2023,IT,Good
1,EMP002,Anita Devi,28,Java,4,600000,2022/05/11,IT,NaN
2,EMP003,Kiran Kumar,31,python,5,720000,15-Jan-2021,IT,Excellent
3,EMP004,Priya Nair,29,Data Science,3,650000,2021-07-20,Analytics,NaN
4,EMP005,Arjun,27,C++,2,520000,10/10/2022,Development,Good

In [88]:
print(df.dtypes)

Employee ID            object
 Employee Name         object
Age                     int64
Skill Set              object
Years of Experience     int64
Salary (INR)           object
Date Of Joining        object
Department             object
Remarks                object
dtype: object

In [153]:
df.rename(columns={"AGE": "Age"}, inplace=True)

In [146]:
df.columns

Index([' Employee Name ', 'Age', 'Skill Set', 'Years of Experience',
       'Salary (INR)', 'Department', 'Remarks_0', 'Remarks_Excellent',
       'Remarks_Good'],
      dtype='object')

In [148]:
#     • Standardize names 

df.columns = df.columns.str.strip()
df["Employee Name"] = df["Employee Name"].str.title()
df["Employee Name"].head()

0     Rahul Sharma
1       Anita Devi
2     Kiran Kumar
3       Priya Nair
4            Arjun
Name: Employee Name, dtype: object

In [152]:
#     • Standardize skills 

df["Skill Set"] = df["Skill Set"].astype(str).str.title()
df["Skill Set"].head()

0    19
1    10
2    19
3     7
4     3
Name: Skill Set, dtype: object

In [151]:
#     • Clean salary values 
print(df["Salary (INR)"].unique())

[-1.02318498 -0.2761694   0.32144307 -0.0271642  -0.67457771  0.6202493
  1.46686697 -1.77020057  2.71189294  0.96885658 -0.52517459 -0.87378187
 -0.82398083  0.22184099  1.21786177  0.71985138 -2.01920576 -0.17656732
 -0.32597044  0.12223891  1.71587216 -0.22636836  0.47084619 -0.77417979
 -1.52119537  1.61627008  0.52064723 -1.67059849  2.21388255 -1.86980264
  1.31746385 -0.72437875  0.17203995 -0.37577148 -0.07696524 -1.37179225
 -0.97338394 -1.72039953  1.66607112]

In [97]:
df["Salary (INR)"] = df["Salary (INR)"].replace({"5,50,000": "550000","650000 INR": "650000","$500000": "500000",
    "4.8L": "480000","Nine Lakhs": "900000","99999999": "990000",0: "500000"})
df

,Employee ID,Employee Name,Age,Skill Set,Years of Experience,Salary (INR),Date Of Joining,Department,Remarks
0,EMP001,Rahul Sharma,25,Python,2,450000,12-01-2023,IT,Good
1,EMP002,Anita Devi,28,Java,4,600000,2022/05/11,IT,0
2,EMP003,Kiran Kumar,31,Python,5,720000,15-Jan-2021,IT,Excellent
3,EMP004,Priya Nair,29,Data Science,3,650000,2021-07-20,Analytics,0
4,EMP005,Arjun,27,C++,2,520000,10/10/2022,Development,Good
...,...,...,...,...,...,...,...,...,...
86,EMP086,Koushik,28,Machine Learning,4,720000,2021-12-12,AI,0
87,EMP087,Aarthi,24,Python,1,350000,2024-01-10,IT,0
88,EMP088,Pradeep,33,Data Science,8,1100000,2016-04-14,Analytics,0
89,EMP089,Rohini,29,Sql,4,650000,2021-08-20,Database,0
90,EMP090,Vijay,28,C++,3,580000,2022-09-09,Development,0

In [123]:
#     • Parse dates 
print(df["Date Of Joining"].dtype)

object

In [125]:
#     • Detect and remove outliers 
Q1 = df["Salary (INR)"].quantile(0.25)
Q3 = df["Salary (INR)"].quantile(0.75)
IQR = Q3 - Q1
df = df[(df["Salary (INR)"] >= Q1 - 1.5 * IQR) & (df["Salary (INR)"] <= Q3 + 1.5 * IQR)]
df.shape
print("Rows after removing outliers:", df.shape[0])

Rows after removing outliers: 88

In [126]:
#     • Validate ages and experience 
df = df[(df["Age"] >= 18) & (df["Years of Experience"] >= 0) & (df["Years of Experience"] <= df["Age"])]
print(df)

   Employee ID  Employee Name   Age  Skill Set  Years of Experience  \
0       EMP001    Rahul Sharma   25         19                    2
1       EMP002      Anita Devi   28         10                    4
2       EMP003    Kiran Kumar    31         19                    5
3       EMP004      Priya Nair   29          7                    3
4       EMP005           Arjun   27          3                    2
..         ...             ...  ...        ...                  ...
86      EMP086         Koushik   28         13                    4
87      EMP087          Aarthi   24         19                    1
88      EMP088         Pradeep   33          7                    8
89      EMP089          Rohini   29         21                    4
90      EMP090           Vijay   28          3                    3

    Salary (INR) Date Of Joining  Department    Remarks
0         450000      12-01-2023           6       Good
1         600000      2022/05/11           6          0
2         720000     15-Jan-2021           6  Excellent
3         650000      2021-07-20           1          0
4         520000      10/10/2022           4       Good
..           ...             ...         ...        ...
86        720000      2021-12-12           0          0
87        350000      2024-01-10           6          0
88       1100000      2016-04-14           1          0
89        650000      2021-08-20           3          0
90        580000      2022-09-09           4          0

[88 rows x 9 columns]

In [130]:
#     • Encode categorical variables 
df = pd.get_dummies(df, columns=["Remarks"])
df.head()

,Employee ID,Employee Name,Age,Skill Set,Years of Experience,Salary (INR),Date Of Joining,Department,Remarks_0,Remarks_Excellent,Remarks_Good
0,EMP001,Rahul Sharma,25,19,2,450000,12-01-2023,6,False,False,True
1,EMP002,Anita Devi,28,10,4,600000,2022/05/11,6,True,False,False
2,EMP003,Kiran Kumar,31,19,5,720000,15-Jan-2021,6,False,True,False
3,EMP004,Priya Nair,29,7,3,650000,2021-07-20,1,True,False,False
4,EMP005,Arjun,27,3,2,520000,10/10/2022,4,False,False,True

In [132]:
#     • Scale numerical columns 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df[["Age", "Years of Experience", "Salary (INR)"]] = scaler.fit_transform(df[["Age", "Years of Experience", "Salary (INR)"]])
df.head()

,Employee ID,Employee Name,Age,Skill Set,Years of Experience,Salary (INR),Date Of Joining,Department,Remarks_0,Remarks_Excellent,Remarks_Good
0,EMP001,Rahul Sharma,-1.037864,19,-0.768382,-1.023185,12-01-2023,6,False,False,True
1,EMP002,Anita Devi,-0.109064,10,-0.004341,-0.276169,2022/05/11,6,True,False,False
2,EMP003,Kiran Kumar,0.819737,19,0.377679,0.321443,15-Jan-2021,6,False,True,False
3,EMP004,Priya Nair,0.200536,7,-0.386362,-0.027164,2021-07-20,1,True,False,False
4,EMP005,Arjun,-0.418664,3,-0.768382,-0.674578,10/10/2022,4,False,False,True

In [137]:
#     • Feature selection
df = df.drop(["Employee ID", "Date Of Joining"], axis=1, errors="ignore")
df.head()

,Employee Name,Age,Skill Set,Years of Experience,Salary (INR),Department,Remarks_0,Remarks_Excellent,Remarks_Good
0,Rahul Sharma,-1.037864,19,-0.768382,-1.023185,6,False,False,True
1,Anita Devi,-0.109064,10,-0.004341,-0.276169,6,True,False,False
2,Kiran Kumar,0.819737,19,0.377679,0.321443,6,False,True,False
3,Priya Nair,0.200536,7,-0.386362,-0.027164,1,True,False,False
4,Arjun,-0.418664,3,-0.768382,-0.674578,4,False,False,True